services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-scraper-tester
    environment:
      - PYTEST_ADDOPTS=--disable-warnings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    shm_size: '2gb'
    ipc: host
    cap_add:
      - SYS_ADMIN
    init: true
    command: >
      sh -c "
        echo 'Running tests (excluding slow external tests)...';
        pytest -v -rs -m 'not slow' tests
      "
    stop_signal: SIGINT

  test-all:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-scraper-tester-all
    environment:
      - PYTEST_ADDOPTS=--disable-warnings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    shm_size: '2gb'
    ipc: host
    cap_add:
      - SYS_ADMIN
    init: true
    security_opt:
      - seccomp:unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
    command: >
      sh -c "
        echo 'Running ALL tests (including slow external tests)...';
        pytest -v -rs tests
      "
    stop_signal: SIGINT

  test-unit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-scraper-tester-unit
    environment:
      - PYTEST_ADDOPTS=--disable-warnings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    shm_size: '2gb'
    ipc: host
    cap_add:
      - SYS_ADMIN
    init: true
    command: >
      sh -c "
        echo 'Running UNIT tests...';
        pytest tests/unit/ --tb=short -v
        "
    stop_signal: SIGINT

  test-integration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-scraper-tester-integration
    environment:
      - PYTEST_ADDOPTS=--disable-warnings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    shm_size: '2gb'
    ipc: host
    cap_add:
      - SYS_ADMIN
    init: true
    command: >
      sh -c "
        echo 'Running INTEGRATION tests...';
        pytest -v -rs -m 'integration and not slow' tests/integration/
      "
    stop_signal: SIGINT
