[pytest]
addopts = --strict-markers
testpaths = tests
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    flaky: marks tests as flaky and allows reruns
filterwarnings =
    ignore::DeprecationWarning
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S

[tool:pytest]
integration_tests_path = tests/integration
asyncio_mode = auto 