import os

# Default configuration values
DEFAULT_TIMEOUT_SECONDS = 30
DEFAULT_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
DEFAULT_VIEWPORT_WIDTH = 1920
DEFAULT_VIEWPORT_HEIGHT = 1080
DEFAULT_PORT = 9001

# Load configuration from environment variables or use defaults
TIMEOUT_SECONDS = int(os.getenv("SCRAPER_TIMEOUT_SECONDS", DEFAULT_TIMEOUT_SECONDS))
USER_AGENT = os.getenv("SCRAPER_USER_AGENT", DEFAULT_USER_AGENT)
VIEWPORT_WIDTH = int(os.getenv("SCRAPER_VIEWPORT_WIDTH", DEFAULT_VIEWPORT_WIDTH))
VIEWPORT_HEIGHT = int(os.getenv("SCRAPER_VIEWPORT_HEIGHT", DEFAULT_VIEWPORT_HEIGHT))
PORT = int(os.getenv("PORT", DEFAULT_PORT)) 